# Generated by Django 3.0.4 on 2020-03-26 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comentarios', '0001_initial'),
        ('enderecos', '__first__'),
        ('avaliacoes', '0001_initial'),
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descrição', models.TextField(verbose_name='descrição')),
                ('aprovado', models.BooleanField(verbose_name='aprovado')),
                ('atracao', models.ManyToManyField(to='atracoes.Atracao')),
                ('avaliacao', models.ManyToManyField(to='avaliacoes.Avaliacoes')),
                ('comentario', models.ManyToManyField(to='comentarios.Comentario')),
                ('enderoco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enderecos.Endereco')),
            ],
        ),
    ]
